# Medium Transformer Configuration
model:
  tokenizer: "bpe-medium"
  embedding_size: 384
  context_size: 256
  num_layers: 8
  num_heads: 12
  d_key: 64
  d_value: 64
  d_ff: 1536
  dropout: 0.1

training:
  batch_size: 64
  learning_rate: 0.0003
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  max_epochs: -1
  epoch_steps: 100
  warmup_steps: 1500
  patience: 4
  stopping_threshold: 0.0001