# Large Transformer Configuration
model:
  tokenizer: "bpe-large"
  embedding_size: 512
  context_size: 512
  num_layers: 12
  num_heads: 12
  d_key: 128
  d_value: 128
  d_ff: 2048
  dropout: 0.1

training:
  batch_size: 256 
  learning_rate: 0.0003
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  num_epochs: -1
  warmup_steps: 4000
  patience: 3