# Tiny Transformer Configuration
model:
  tokenizer: "bpe-tiny"
  embedding_size: 128
  context_size: 64
  num_layers: 4
  num_heads: 4
  d_key: 32
  d_value: 32
  d_ff: 256
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  max_epochs: 250
  epoch_steps: 1500
  warmup_steps: 500
  patience: 5
  stopping_threshold: 0.0001