# Small Base Configuration
model:
  tokenizer: "bpe-small"
  embedding_size: 256
  context_size: 256
  num_layers: 6
  num_heads: 8
  d_key: 64
  d_value: 64
  d_ff: 1024
  dropout: 0.1

training:
  batch_size: 64
  learning_rate: 0.0003
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  max_epochs: 300
  epoch_steps: 150
  warmup_steps: 300
  patience: 10
  stopping_threshold: 0.0001