# Tiny Transformer Configuration
model:
  tokenizer: "bpe-small"
  embedding_size: 128
  context_size: 64
  num_layers: 4
  num_heads: 8
  d_key: 32
  d_value: 32
  d_ff: 512
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.0003
  weight_decay: 0.01
  gradient_clip_norm: 1.0
  num_epochs: 1
  warmup_steps: 500
  patience: 5