import dataclasses
import logging
import string
import time
from typing import Any

from lumiere import Loader, register_dependency
from lumiere.utils import randomizer

from .artifact import ArtifactStore
from .checkpoint import Checkpoint, CheckpointStore, CheckpointTag
from .config import Config
from .errors import CheckpointNotFoundError, RunNotFoundError
from .event import EventStore
from .loss import cross_entropy_loss
from .run import Run, RunStatus, RunStore
from .trainer import Trainer, TrainingState


logger = logging.getLogger(__name__)


@dataclasses.dataclass
class TrainingArguments:
    """Parameters to control training runs.

    Attributes:
        max_epochs: The maximum number epochs to be executed. If none is provided the
            run will execute indefinitely or until either it's patience is exceeded or
            it is forcefully stopped via a signal.
        patience: The maximum number of consecutive epochs allowed without improvement.
            Exceeding this number halts the training run.
        stopping_threshold: The minimum improvement to the validation performance for
            this epoch to count as an improvement.
        gradient_clip_norm: The maximum normal of the gradient weights.
        log_interval: The number of steps between each capture or training metrics.
        checkpoint_interval: The number of epochs between saving each checkpoint.
        device: The device training should be executed on.

    """

    max_epochs: int | None = 25
    patience: int | None = 3
    stopping_threshold: float | None = 1e-3
    gradient_clip_norm: float | None = 1e-1
    log_interval: int | None = 50
    checkpoint_interval: int | None = 5
    device: str | None = "cpu"


class TrainingOrchestrator:
    """Orchestrates and executes training runs.

    An orchestrator is responsible for ensuring that all components needed to execute
    a training run are initialized or loaded successfully and that they are
    coordinated to successfully complete the training run.

    To ensure that training runs can be interrupted and resumed at a later time, an
    orchestrator stores several artifacts. Artifacts are categorized by type and to
    allow flexibility in storage locations, each designated artifact type uses its
    own store.
    """

    def __init__(
        self,
        run_store: RunStore,
        checkpoint_store: CheckpointStore,
        artifact_store: ArtifactStore,
        event_store: EventStore,
    ):
        """Initialize a TrainingOrchestrator.

        Args:
            run_store: The store for training runs.
            checkpoint_store: The store for training checkpoints.
            artifact_store: The store for training artifacts.
            event_store: The store for training events.

        """
        self.run_store = run_store
        self.checkpoint_store = checkpoint_store
        self.artifact_store = artifact_store
        self.event_store = event_store

        # TODO: Move to closure in _register_training_hooks method.
        self._buffer: dict[str, Any] = {}

    def start(
        self,
        config: Config,
        args: TrainingArguments,
        run_name: str | None = None,
    ):
        """Start a new training run.

        Args:
            config: The configuration to be used for the training run.
            args: The parameters controlling the training run.
            run_name: The name of the training run to be resumed. If none is provided
                one will be autogenerated.

        """
        logger.info("Initializing a new training run...")
        if run_name is None or len(run_name.strip(string.whitespace)) == 0:
            run_name = randomizer.random_name()

        run, trainer = self._init_training_run(run_name, config, args)
        logger.info(f"Run '{run_name}' successfully initialized. Starting run...")

        # TODO: Execute this asynchronously.
        train_metrics = trainer.train()

        logger.info(
            f"Training completed in {_format_hours(train_metrics.total_time_taken)}!"
        )
        run.status = RunStatus.COMPLETED
        run.updated_at = time.time_ns()
        self.run_store.update(run)

        # self.checkpoint_store.mark_final()

        return run

    def _init_training_run(
        self, name: str, config: Config, args: TrainingArguments
    ) -> tuple[Run, Trainer]:
        """Initialize components for a new training run."""
        # Validate early to avoid partially loading components.
        # TODO: Raise ValueError if required config fields are missing.
        # fmt: off
        assert config.get("tokenizer") is not None, "Config missing required 'tokenizer' section"   # NOQA: E501
        assert config.get("data") is not None, "Config missing required 'data' section"             # NOQA: E501
        assert config.get("pipeline") is not None, "Config missing required 'pipeline' section"     # NOQA: E501
        assert config.get("model") is not None, "Config missing required 'model' section"           # NOQA: E501
        assert config.get("optimizer") is not None, "Config missing required 'optimizer' section"   # NOQA: E501
        # fmt: on

        # Capture the training params so they can be reused when resuming runs.
        config["training"] = dataclasses.asdict(args)
        run = Run(config, name=name)
        try:
            self.run_store.add(run)
        except Exception as e:
            logger.error(f"Failed to initialize training run '{run.name}'.")
            raise e
        logger.info(
            f"Successfully initialized training run '{run.name}' (ID: {run.id})."
        )

        try:
            logger.info("Loading dataset...")
            dataloader = Loader.data(run.config["data"])
            logger.info(
                f"Dataloader initialized with {len(dataloader.datasets)} dataset(s)"
            )

            logger.info("Loading tokenizer...")
            tokenizer = Loader.tokenizer(run.config["tokenizer"])
            register_dependency("tokenizer", tokenizer)
            logger.info("Tokenizer loaded successfully")

            logger.info("Training tokenizer on training data...")
            tokenizer.train(dataloader["train"])
            logger.info(
                f"Tokenizer trained successfully (vocab size: {tokenizer.vocab_size})"
            )

            logger.info("Saving tokenizer artifact...")
            self.artifact_store.add(run.name, "tokenizer", bytes(tokenizer))
            logger.info("Tokenizer artifact saved successfully")

            logger.info("Loading pipeline...")
            pipeline = Loader.pipeline(config["pipeline"])
            logger.info("Pipeline loaded successfully")

            logger.info("Building model...")
            model = Loader.model(config["model"])
            total_params = sum(p.numel() for p in model.parameters())
            trainable_params = sum(
                p.numel() for p in model.parameters() if p.requires_grad
            )
            logger.info(
                f"Model built successfully - "
                f"Total params: {total_params:,}, Trainable: {trainable_params:,}"
            )

            logger.info("Loading optimizer...")
            optimizer = Loader.optimizer(config["optimizer"], model.parameters())
            logger.info(f"Optimizer loaded: {type(optimizer).__name__}")

            scheduler = None
            if (scheduler_config := config.get("scheduler")) is not None:
                logger.info("Loading learning rate scheduler...")
                scheduler = Loader.scheduler(scheduler_config, optimizer)
                logger.info(f"Scheduler loaded: {type(scheduler).__name__}")

            logger.info("All components initialized successfully")
        except Exception as e:
            logger.error(
                "Failed to initialize training components for run '{run.name}'."
            )
            run.status = RunStatus.ERROR
            self.run_store.update(run)
            raise e

        trainer = Trainer(
            model=model,
            dataloader=dataloader,
            pipeline=pipeline,
            loss_fn=cross_entropy_loss,
            optimizer=optimizer,
            scheduler=scheduler,
            max_epochs=args.max_epochs,
            stopping_threshold=args.stopping_threshold,
            patience=args.patience,
            gradient_clip_norm=args.gradient_clip_norm,
            device=args.device,
        )

        self._register_training_hooks(run, trainer)

        return run, trainer

    def resume(self, run_name: str, checkpoint_tag: str = "latest"):
        """Resume a previously interrupted training run.

        Args:
            run_name: The name of the training run to be resumed.
            checkpoint_tag: The checkpoint to resume training from. Defaults to
                `'latest'`.
        """
        if run_name is None or len(run_name.strip()) == 0:
            raise ValueError("No run rame was provided.")

        if checkpoint_tag is None:
            logger.debug(
                "No checkpoint specified as the restore point for training run"
                + "'{run_name}'. Defaulting to 'latest'."
            )
            checkpoint_tag = str(CheckpointTag.LATEST)

        logger.info(
            f"Resuming training run '{run_name}' from checkpoint '{checkpoint_tag}'..."  # NOQA: E501
        )
        run, trainer = self._load_training_run(run_name, checkpoint_tag)

        logger.info("Trainer initialized successfully, starting run '{run.name}'...")
        train_metrics = trainer.train()
        logger.info(
            f"Training completed in {_format_hours(train_metrics.total_time_taken)}!"
        )

        run.status = RunStatus.COMPLETED
        run.updated_at = time.time_ns()
        self.run_store.update(run)

        # self.checkpoint_store.mark_final()

        return run

    def _load_training_run(
        self, run_name: str, checkpoint_tag: CheckpointTag | str
    ) -> tuple[Run, Trainer]:
        """Load components from a previous training run."""
        logger.debug(f"Loading training run '{run_name}' from storage.")
        run = self.run_store.get(run_name)
        if run is None:
            raise RunNotFoundError(run_name)

        logger.debug(f"Successfully retrieved run '{run_name}'.\n{run.to_dict()}")

        # fmt: off
        config = run.config
        assert config.get("tokenizer") is not None, "Config missing required 'tokenizer' section"   # NOQA: E501
        assert config.get("data") is not None, "Config missing required 'data' section"             # NOQA: E501
        assert config.get("pipeline") is not None, "Config missing required 'pipeline' section"     # NOQA: E501
        assert config.get("model") is not None, "Config missing required 'model' section"           # NOQA: E501
        assert config.get("optimizer") is not None, "Config missing required 'optimizer' section"   # NOQA: E501
        assert config.get("training") is not None, "Config missing required 'training' section"     # NOQA: E501
        # fmt: on

        checkpoint = self.checkpoint_store.get(
            run_name, checkpoint_tag, device=config["training.device"]
        )
        if checkpoint is None:
            raise CheckpointNotFoundError(run_name, checkpoint_tag)
        logger.debug(
            f"Successfully retrieved checkpoint '{checkpoint_tag}' from storage.\n"
            + f"{checkpoint.meta()}"
        )

        logger.info("Loading tokenizer...")
        tokenizer_data = self.artifact_store.get(run_name, "tokenizer")
        if tokenizer_data is None:
            raise RuntimeError(f"No tokenizer found for run '{run_name}'.")
        tokenizer = Loader.tokenizer(config["tokenizer"], state=tokenizer_data)
        register_dependency("tokenizer", tokenizer)
        logger.info("Tokenizer loaded successfully")

        logger.info("Loading dataset...")
        dataloader = Loader.data(config["data"])
        logger.info(
            f"Dataloader initialized with {len(dataloader.datasets)} dataset(s)"
        )

        logger.info("Loading pipeline...")
        pipeline = Loader.pipeline(config["pipeline"]).to(config["training.device"])
        logger.info("Pipeline loaded successfully")

        logger.info("Building model...")
        model = Loader.model(config["model"])
        model.load_state_dict(checkpoint.model_state_dict, strict=True, assign=True)
        total_params = sum(p.numel() for p in model.parameters())
        trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
        logger.info(
            f"Model loaded successfully - "
            f"Total params: {total_params:,}, Trainable: {trainable_params:,}"
        )

        logger.info("Loading optimizer...")
        optimizer = Loader.optimizer(config["optimizer"], model.parameters())
        optimizer.load_state_dict(checkpoint.optimizer_state_dict)
        logger.info(f"Optimizer loaded: {type(optimizer).__name__}")

        scheduler = None
        scheduler_config = config.get("scheduler")
        if scheduler_config is not None:
            logger.info("Loading scheduler...")
            scheduler = Loader.scheduler(scheduler_config, optimizer)
            scheduler.load_state_dict(checkpoint.scheduler_state_dict)
            logger.info(f"Scheduler loaded: {type(scheduler).__name__}")

        logger.info("All components loaded successfully from checkpoint")

        training_state = TrainingState.from_dict(checkpoint.training_state)
        logger.info(
            f"Resuming run '{run_name}' from epoch {training_state.current_epoch}."
        )

        trainer = Trainer(
            model=model,
            dataloader=dataloader,
            pipeline=pipeline,
            loss_fn=cross_entropy_loss,
            optimizer=optimizer,
            scheduler=scheduler,
            state=training_state,
            max_epochs=config["training.max_epochs"],
            stopping_threshold=config["training.stopping_threshold"],
            patience=config["training.patience"],
            gradient_clip_norm=config["training.gradient_clip_norm"],
            device=config["training.device"],
        )
        self._register_training_hooks(run, trainer)

        return run, trainer

    def _register_training_hooks(self, run: Run, trainer: Trainer) -> None:
        def _capture_train_loss(trainer: Trainer, train_metrics) -> None:
            self._buffer["train_loss"] = train_metrics.avg_loss.item()

        def _capture_val_loss(trainer: Trainer, eval_metrics) -> None:
            self._buffer["val_loss"] = eval_metrics.avg_loss.item()

        def _save_epoch_stats(trainer: Trainer) -> None:
            self.event_store.add(
                run.name,
                {
                    "train_loss": self._buffer.get("train_loss", 0.0),
                    "val_loss": self._buffer.get("val_loss", 0.0),
                    "lr": trainer.state.current_lr,
                    "epoch": trainer.state.current_epoch,
                    "global_step": trainer.state.global_step,
                },
            )

        def _save_checkpoint(trainer):
            """Save a checkpoint."""
            # Avoid creating a checkpoint if saving criteria aren't met.
            # TODO: Only skip creation of epoch checkpoints, best / latest should always be created.
            if (
                trainer.state.current_epoch % self.checkpoint_interval != 0
                and trainer.state.prev_loss != trainer.state.best_loss
            ):
                return

            checkpoint = Checkpoint(
                epoch=trainer.state.current_epoch,
                loss=trainer.state.prev_loss.item(),
                training_state=trainer.state_dict(),
                model_state_dict=trainer.model.state_dict(),
                optimizer_state_dict=trainer.optimizer.state_dict(),
            )
            if trainer.scheduler is not None:
                checkpoint.scheduler_state_dict = trainer.scheduler.state_dict()

            logging.info(f"Saving checkpoint '{checkpoint.id}'...")
            self.checkpoint_store.add(run.name, checkpoint)
            logger.info("Checkpoint saved successfully")

        def _update_run(trainer):
            run.current_epoch = trainer.state.current_epoch
            run.current_step = trainer.state.global_step
            run.current_loss = trainer.state.prev_loss.item()
            # TODO: Consider adding total training time as well.
            run.updated_at = time.time_ns()
            self.run_store.update(run)

        trainer.register_post_fit_hook(_capture_train_loss)
        trainer.register_post_eval_hook(_capture_val_loss)
        trainer.register_post_epoch_hook(_save_epoch_stats)
        if run.config["training.checkpoint_interval"]:
            trainer.register_post_epoch_hook(_save_checkpoint)
        trainer.register_post_epoch_hook(_update_run)


def _format_hours(time: float) -> str:
    seconds = int(time)
    minutes, seconds = divmod(seconds, 60)
    hours, minutes = divmod(minutes, 60)
    return f"{hours}H {minutes}m {seconds}s"
